// File generated by FlutterFire CLI.
// Run `dart pub global run flutterfire_cli:flutterfire configure`
// and select your EXISTING Firebase project to populate real values.
// Until then, this stub provides the expected class structure so the
// codebase compiles. Firebase.initializeApp() will fail at runtime until
// the real options are written by `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD246iL5Yx_EAAUkvc4WMVlBi553S1yH4',
    appId: '1:826077245228:web:2a2866e8982317b712c689',
    messagingSenderId: '826077245228',
    projectId: 'axn-a947f',
    authDomain: 'axn-a947f.firebaseapp.com',
    storageBucket: 'axn-a947f.firebasestorage.app',
    measurementId: 'G-MBXV1P92RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltqKnXVcgQekX7RrA9b-Y__Qy6J0UxuE',
    appId: '1:826077245228:android:01c51ef14cf48f7312c689',
    messagingSenderId: '826077245228',
    projectId: 'axn-a947f',
    storageBucket: 'axn-a947f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFlpX3miLqpBjdKYZ8HuLBt2CPToXR3U',
    appId: '1:826077245228:ios:eb5d6463b24cdde012c689',
    messagingSenderId: '826077245228',
    projectId: 'axn-a947f',
    storageBucket: 'axn-a947f.firebasestorage.app',
    iosBundleId: 'com.example.axnApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkFlpX3miLqpBjdKYZ8HuLBt2CPToXR3U',
    appId: '1:826077245228:ios:eb5d6463b24cdde012c689',
    messagingSenderId: '826077245228',
    projectId: 'axn-a947f',
    storageBucket: 'axn-a947f.firebasestorage.app',
    iosBundleId: 'com.example.axnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD246iL5Yx_EAAUkvc4WMVlBi553S1yH4',
    appId: '1:826077245228:web:ae63c16572b4003312c689',
    messagingSenderId: '826077245228',
    projectId: 'axn-a947f',
    authDomain: 'axn-a947f.firebaseapp.com',
    storageBucket: 'axn-a947f.firebasestorage.app',
    measurementId: 'G-BNTSDZ5PER',
  );
}
