import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../theme/app_colors.dart' as theme;
import '../models/app_scope.dart';

/// ============================================================
/// family_account_consent_screen.dart
///
/// Merged single-file version of the `family_account_consent`
/// feature. Generated by combining every file that used to live
/// under lib/family_account_consent/** (plus main.dart) into one
/// .dart file. Entry point: run `runApp(const AxnSafetyApp())`.
/// ============================================================


// ---------------------------------------------------------------
// from: family_account_consent/theme/app_colors.dart
// ---------------------------------------------------------------
/// Color and radius tokens ported 1:1 from the original screen's
/// `:root{ --bg, --surface, --card, ... }` CSS custom properties.
class AppColors {
  AppColors._();

  static const Color bg = Color(0xFFFFFFFF);
  static const Color surface = Color(0xFFF7F7F8);
  static const Color card = Color(0xFFFFFFFF);
  static const Color cardBorder = Color(0xFFEAEAEA);
  static const Color primary = Color(0xFFCE1126);
  static const Color primaryDark = Color(0xFFA50E1F);
  static const Color primaryTint = Color(0x14CE1126); // rgba(206,17,38,0.08)
  static const Color heading = Color(0xFF22252A);
  static const Color body = Color(0xFF6B7280);
  static const Color muted = Color(0xFF9AA1AC);
  static const Color success = Color(0xFF4CAF6D);
  static const Color successBg = Color(0x1F4CAF6D); // rgba(76,175,109,0.12)
  static const Color error = Color(0xFFD64545);
  static const Color errorBg = Color(0x1AD64545); // rgba(214,69,69,0.1)

  static const Color cardShadow = Color(0x08141414); // rgba(20,20,20,0.03)
  static const Color screenShadow = Color(0x0F141414); // rgba(20,20,20,0.06)

  static const double radiusLg = 22;
  static const double radiusMd = 16;
  static const double radiusSm = 11;
}

// ---------------------------------------------------------------
// from: family_account_consent/theme/app_text_styles.dart
// ---------------------------------------------------------------
/// Font notes:
/// The original design uses "Playfair Display" for headings, "Inter" for
/// body copy, and "IBM Plex Mono" for the small uppercase eyebrow/brand
/// labels. Loaded live via google_fonts (already a dependency of this
/// project / used by AxnSafetyApp's theme), so these are real Google
/// Fonts, not generic system fallbacks.
class AppTextStyles {
  AppTextStyles._();

  static TextStyle get brand => GoogleFonts.ibmPlexMono(
        fontSize: 11,
        letterSpacing: 1.54, // .14em of 11px
        fontWeight: FontWeight.w500,
        color: AppColors.muted,
      );

  static TextStyle get heading1 => GoogleFonts.playfairDisplay(
        fontWeight: FontWeight.w600,
        fontSize: 28,
        letterSpacing: -0.56, // -0.02em of 28px
        color: AppColors.heading,
      );

  static TextStyle get headerParagraph => GoogleFonts.inter(
        fontSize: 14.5,
        height: 1.55,
        color: AppColors.body,
      );

  static TextStyle get sectionEyebrow => GoogleFonts.ibmPlexMono(
        fontSize: 11,
        letterSpacing: 1.1, // .1em of 11px
        fontWeight: FontWeight.w500,
        color: AppColors.primary,
      );

  static TextStyle get memberName => GoogleFonts.inter(
        fontSize: 14.5,
        fontWeight: FontWeight.w600,
        color: AppColors.heading,
      );

  static TextStyle get memberRel => GoogleFonts.inter(
        fontSize: 12.5,
        color: AppColors.muted,
      );

  static TextStyle get avatarInitials => GoogleFonts.playfairDisplay(
        fontWeight: FontWeight.w600,
        fontSize: 15,
        color: AppColors.heading,
      );

  static TextStyle get avatarInitialsTint => GoogleFonts.playfairDisplay(
        fontWeight: FontWeight.w600,
        fontSize: 15,
        color: AppColors.primaryDark,
      );

  static TextStyle get statusPill => GoogleFonts.playfairDisplay(
        fontSize: 11.5,
        fontWeight: FontWeight.w600,
      );

  static TextStyle get infoCardTitle => GoogleFonts.playfairDisplay(
        fontSize: 14,
        fontWeight: FontWeight.w600,
        color: AppColors.heading,
      );

  static TextStyle get infoCardBullet => GoogleFonts.inter(
        fontSize: 12.5,
        height: 1.45,
        color: AppColors.body,
      );

  static TextStyle get consentLabel => GoogleFonts.inter(
        fontSize: 13.5,
        height: 1.5,
        color: AppColors.heading,
      );

  static TextStyle get btnPrimary => GoogleFonts.playfairDisplay(
        fontSize: 15,
        fontWeight: FontWeight.w600,
        color: Colors.white,
      );

  static TextStyle get btnSecondary => GoogleFonts.playfairDisplay(
        fontSize: 14,
        fontWeight: FontWeight.w500,
        color: AppColors.body,
      );

  static TextStyle get successHeading => GoogleFonts.playfairDisplay(
        fontSize: 18,
        fontWeight: FontWeight.w600,
        color: AppColors.heading,
      );

  static TextStyle get successParagraph => GoogleFonts.inter(
        fontSize: 13,
        height: 1.5,
        color: AppColors.body,
      );
}

// ---------------------------------------------------------------
// from: family_account_consent/models/family_member.dart
// ---------------------------------------------------------------
enum FamilyMemberStatus { connected, pending, connectable }

@immutable
class FamilyMember {
  const FamilyMember({
    required this.initials,
    required this.name,
    required this.relationship,
    required this.status,
    this.tintedAvatar = false,
  });

  final String initials;
  final String name;
  final String relationship;
  final FamilyMemberStatus status;
  final bool tintedAvatar;
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/pulsing_brand_dot.dart
// ---------------------------------------------------------------
class PulsingBrandDot extends StatefulWidget {
  const PulsingBrandDot({super.key, this.size = 6});

  final double size;

  @override
  State<PulsingBrandDot> createState() => _PulsingBrandDotState();
}

class _PulsingBrandDotState extends State<PulsingBrandDot>
    with SingleTickerProviderStateMixin {
  late final AnimationController _controller;

  @override
  void initState() {
    super.initState();
    // The CSS keyframes run 0% -> 50% -> 100% over 2.4s; a 1.2s
    // reverse-repeating controller reproduces the same ease-in-out cycle.
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1200),
    )..repeat(reverse: true);
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      builder: (context, child) {
        final double t = Curves.easeInOut.transform(_controller.value);
        final double spread = 3 + (3 * t); // 3px -> 6px
        final int alpha = (36 + (13 - 36) * t).round(); // .14 -> .05 alpha
        return Container(
          width: widget.size,
          height: widget.size,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: AppColors.primary,
            boxShadow: [
              BoxShadow(
                color: AppColors.primary.withAlpha(alpha),
                spreadRadius: spread,
                blurRadius: 0,
              ),
            ],
          ),
        );
      },
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/brand_header.dart
// ---------------------------------------------------------------
class BrandHeader extends StatelessWidget {
  const BrandHeader({super.key, this.onClose});

  final VoidCallback? onClose;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Row(
          children: [
            const PulsingBrandDot(),
            const SizedBox(width: 8),
            Text(scope.t('family_brand'), style: AppTextStyles.brand.copyWith(color: theme.AppColors.mutedOf(context))),
          ],
        ),
        GestureDetector(
          onTap: onClose,
          child: Container(
            width: 30,
            height: 30,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              border: Border.all(color: theme.AppColors.border(context)),
            ),
            child: Text(
              '✕',
              style: TextStyle(fontSize: 14, color: theme.AppColors.mutedOf(context)),
            ),
          ),
        ),
      ],
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/section_eyebrow.dart
// ---------------------------------------------------------------
class SectionEyebrow extends StatelessWidget {
  const SectionEyebrow(this.text, {super.key});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsetsDirectional.only(bottom: 10),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 12,
            height: 1,
            color: AppColors.primary.withOpacity(0.6),
          ),
          const SizedBox(width: 8),
          Text(text.toUpperCase(), style: AppTextStyles.sectionEyebrow),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/status_pill.dart
// ---------------------------------------------------------------
class StatusPill extends StatelessWidget {
  const StatusPill({super.key, required this.status, this.onConnectTap});

  final FamilyMemberStatus status;
  final VoidCallback? onConnectTap;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return switch (status) {
      FamilyMemberStatus.connected => _buildPill(
          label: scope.t('family_statusConnected'),
          background: AppColors.successBg,
          textColor: AppColors.success,
        ),
      FamilyMemberStatus.pending => _buildPill(
          label: scope.t('family_statusPending'),
          background: theme.AppColors.surf(context),
          textColor: theme.AppColors.mutedOf(context),
        ),
      FamilyMemberStatus.connectable => GestureDetector(
          onTap: onConnectTap,
          child: _buildPill(
            label: scope.t('family_statusConnect'),
            background: Colors.transparent,
            textColor: AppColors.primary,
            border: Border.all(color: AppColors.primary),
          ),
        ),
    };
  }

  Widget _buildPill({
    required String label,
    required Color background,
    required Color textColor,
    Border? border,
  }) {
    return Container(
      padding: const EdgeInsetsDirectional.symmetric(horizontal: 10, vertical: 5),
      decoration: BoxDecoration(
        color: background,
        border: border,
        borderRadius: BorderRadius.circular(100),
      ),
      child: Text(
        label,
        style: AppTextStyles.statusPill.copyWith(color: textColor),
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/consent_checkbox.dart
// ---------------------------------------------------------------
class ConsentCheckbox extends StatelessWidget {
  const ConsentCheckbox({
    super.key,
    required this.value,
    required this.onChanged,
  });

  final bool value;
  final ValueChanged<bool> onChanged;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => onChanged(!value),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 180),
        curve: Curves.easeOut,
        margin: const EdgeInsetsDirectional.only(top: 1),
        width: 20,
        height: 20,
        decoration: BoxDecoration(
          color: value ? AppColors.primary : theme.AppColors.cardBgOf(context),
          borderRadius: BorderRadius.circular(6),
          border: Border.all(
            color: value ? AppColors.primary : theme.AppColors.border(context),
            width: 1.5,
          ),
        ),
        child: value
            ? const Icon(Icons.check, size: 14, color: Colors.white)
            : null,
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/consent_row.dart
// ---------------------------------------------------------------
class ConsentRow extends StatelessWidget {
  const ConsentRow({
    super.key,
    required this.value,
    required this.onChanged,
  });

  final bool value;
  final ValueChanged<bool> onChanged;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return Container(
      margin: const EdgeInsetsDirectional.only(top: 2, bottom: 16),
      padding: const EdgeInsetsDirectional.all(14),
      decoration: BoxDecoration(
        color: theme.AppColors.surf(context),
        border: Border.all(color: theme.AppColors.border(context)),
        borderRadius: BorderRadius.circular(AppColors.radiusMd),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ConsentCheckbox(value: value, onChanged: onChanged),
          const SizedBox(width: 10),
          Expanded(
            child: GestureDetector(
              onTap: () => onChanged(!value),
              child: Text(
                scope.t('family_consentLabel'),
                style: AppTextStyles.consentLabel.copyWith(color: theme.AppColors.textP(context)),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/primary_button.dart
// ---------------------------------------------------------------
class AppPrimaryButton extends StatefulWidget {
  const AppPrimaryButton({
    super.key,
    required this.label,
    required this.enabled,
    required this.onPressed,
    this.loading = false,
    this.loadingLabel,
    this.mutedStyle = false,
  });

  final String label;
  final bool enabled;
  final VoidCallback? onPressed;
  final bool loading;
  final String? loadingLabel;

  /// Matches the "Done" button variant, which reuses .btn-primary but with
  /// a surface background and heading-colored text instead of the red fill.
  final bool mutedStyle;

  @override
  State<AppPrimaryButton> createState() => _AppPrimaryButtonState();
}

class _AppPrimaryButtonState extends State<AppPrimaryButton> {
  bool _pressed = false;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    final bool isActive = widget.enabled && !widget.loading;
    final Color background = widget.mutedStyle
        ? theme.AppColors.surf(context)
        : (isActive ? AppColors.primary : theme.AppColors.surf(context));
    final Color textColor = widget.mutedStyle
        ? theme.AppColors.textP(context)
        : (isActive ? Colors.white : theme.AppColors.mutedOf(context));
    final List<BoxShadow> shadow = (isActive && !widget.mutedStyle)
        ? [
            BoxShadow(
              color: AppColors.primary.withOpacity(0.45),
              blurRadius: 20,
              offset: const Offset(0, 8),
              spreadRadius: -8,
            ),
          ]
        : const [];

    return GestureDetector(
      onTapDown: isActive ? (_) => setState(() => _pressed = true) : null,
      onTapUp: isActive ? (_) => setState(() => _pressed = false) : null,
      onTapCancel: isActive ? () => setState(() => _pressed = false) : null,
      onTap: isActive ? widget.onPressed : null,
      child: AnimatedScale(
        scale: _pressed ? 0.99 : 1.0,
        duration: const Duration(milliseconds: 150),
        curve: Curves.easeOut,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 150),
          curve: Curves.easeOut,
          width: double.infinity,
          padding: const EdgeInsetsDirectional.all(16),
          decoration: BoxDecoration(
            color: background,
            borderRadius: BorderRadius.circular(100),
            boxShadow: shadow,
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: widget.loading
                ? [
                    SizedBox(
                      width: 17,
                      height: 17,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation(
                          widget.mutedStyle ? theme.AppColors.textP(context) : Colors.white,
                        ),
                        backgroundColor: widget.mutedStyle
                            ? theme.AppColors.textP(context).withOpacity(0.2)
                            : const Color(0x59FFFFFF),
                      ),
                    ),
                    const SizedBox(width: 9),
                    Text(
                      widget.loadingLabel ?? scope.t('family_connecting'),
                      style: AppTextStyles.btnPrimary.copyWith(
                        color: widget.mutedStyle ? theme.AppColors.textP(context) : Colors.white,
                      ),
                    ),
                  ]
                : [
                    Text(
                      widget.label,
                      style: AppTextStyles.btnPrimary.copyWith(
                        color: textColor,
                      ),
                    ),
                  ],
          ),
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/secondary_button.dart
// ---------------------------------------------------------------
class AppSecondaryButton extends StatefulWidget {
  const AppSecondaryButton({
    super.key,
    required this.label,
    required this.onPressed,
  });

  final String label;
  final VoidCallback? onPressed;

  @override
  State<AppSecondaryButton> createState() => _AppSecondaryButtonState();
}

class _AppSecondaryButtonState extends State<AppSecondaryButton> {
  bool _hovering = false;

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => setState(() => _hovering = true),
      onExit: (_) => setState(() => _hovering = false),
      cursor: SystemMouseCursors.click,
      child: GestureDetector(
        onTap: widget.onPressed,
        child: Container(
          width: double.infinity,
          padding: const EdgeInsetsDirectional.all(15),
          alignment: Alignment.center,
          color: Colors.transparent,
          child: Text(
            widget.label,
            style: AppTextStyles.btnSecondary.copyWith(
              color: _hovering ? theme.AppColors.textP(context) : theme.AppColors.textS(context),
            ),
          ),
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/consent_default_view.dart
// ---------------------------------------------------------------
class ConsentDefaultView extends StatelessWidget {
  const ConsentDefaultView({
    super.key,
    required this.consentChecked,
    required this.onConsentChanged,
    required this.isConnecting,
    required this.onConnectPressed,
    required this.onNotNowPressed,
  });

  final bool consentChecked;
  final ValueChanged<bool> onConsentChanged;
  final bool isConnecting;
  final VoidCallback onConnectPressed;
  final VoidCallback onNotNowPressed;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return Column(
      children: [
        ConsentRow(value: consentChecked, onChanged: onConsentChanged),
        AppPrimaryButton(
          label: scope.t('family_connectMemberBtn'),
          enabled: consentChecked,
          loading: isConnecting,
          onPressed: onConnectPressed,
        ),
        AppSecondaryButton(label: scope.t('family_notNowBtn'), onPressed: onNotNowPressed),
      ],
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/success_link_graphic.dart
// ---------------------------------------------------------------
/// Recreates the `.link-node-wrap` graphic: two avatar "nodes" connected by
/// a line that draws in, plus a pulse dot that continuously travels from
/// node A to node B once the entrance animation has settled.
class SuccessLinkGraphic extends StatefulWidget {
  const SuccessLinkGraphic({super.key, required this.active});

  final bool active;

  @override
  State<SuccessLinkGraphic> createState() => _SuccessLinkGraphicState();
}

class _SuccessLinkGraphicState extends State<SuccessLinkGraphic>
    with TickerProviderStateMixin {
  static const int _entranceMs = 750;

  late final AnimationController _entranceController;
  late final AnimationController _pulseController;

  @override
  void initState() {
    super.initState();
    _entranceController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: _entranceMs),
    );
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1400),
    );
    if (widget.active) _play();
  }

  @override
  void didUpdateWidget(covariant SuccessLinkGraphic oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.active && !oldWidget.active) {
      _play();
    } else if (!widget.active && oldWidget.active) {
      _stop();
    }
  }

  void _play() {
    _entranceController.forward(from: 0);
    _pulseController.stop();
    _pulseController.reset();
    // CSS: .link-pulse animation-delay is .75s, independent of the entrance
    // timings, so it is scheduled the same way here.
    Future.delayed(const Duration(milliseconds: 750), () {
      if (mounted && widget.active) {
        _pulseController.repeat();
      }
    });
  }

  void _stop() {
    _entranceController.stop();
    _entranceController.reset();
    _pulseController.stop();
    _pulseController.reset();
  }

  @override
  void dispose() {
    _entranceController.dispose();
    _pulseController.dispose();
    super.dispose();
  }

  Animation<double> _interval(int startMs, int durationMs) {
    final double start = startMs / _entranceMs;
    final double end = ((startMs + durationMs) / _entranceMs).clamp(0.0, 1.0);
    return CurvedAnimation(
      parent: _entranceController,
      curve: Interval(start, end, curve: Curves.easeOutCubic),
    );
  }

  @override
  Widget build(BuildContext context) {
    final Animation<double> nodeA = _interval(0, 500);
    final Animation<double> nodeB = _interval(50, 500);
    final Animation<double> line = _interval(150, 600);

    const double wrapWidth = 180;
    const double wrapHeight = 70;
    const double nodeSize = 46;

    return SizedBox(
      width: wrapWidth,
      height: wrapHeight,
      child: AnimatedBuilder(
        animation: Listenable.merge([_entranceController, _pulseController]),
        builder: (context, child) {
          return Stack(
            clipBehavior: Clip.none,
            children: [
              // Connecting line
              PositionedDirectional(
                top: 35,
                start: nodeSize,
                end: nodeSize,
                height: 2,
                child: Transform(
                  alignment: AlignmentDirectional.centerStart,
                  transform: Matrix4.identity()..scale(line.value, 1.0),
                  child: Container(color: AppColors.primary.withOpacity(0.35)),
                ),
              ),
              // Traveling pulse dot
              _buildPulseDot(wrapWidth),
              // Node A (parent)
              PositionedDirectional(
                top: 12,
                start: 0,
                child: Opacity(
                  opacity: nodeA.value.clamp(0.0, 1.0),
                  child: Transform.scale(
                    scale: 0.6 + (0.4 * nodeA.value),
                    child: _buildNode(
                      label: 'PA',
                      background: theme.AppColors.surf(context),
                      textColor: theme.AppColors.textP(context),
                      border: Border.all(color: theme.AppColors.border(context)),
                    ),
                  ),
                ),
              ),
              // Node B (child)
              PositionedDirectional(
                top: 12,
                end: 0,
                child: Opacity(
                  opacity: nodeB.value.clamp(0.0, 1.0),
                  child: Transform.scale(
                    scale: 0.6 + (0.4 * nodeB.value),
                    child: _buildNode(
                      label: 'CH',
                      background: AppColors.primary,
                      textColor: Colors.white,
                      border: null,
                    ),
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }

  Widget _buildPulseDot(double wrapWidth) {
    final double t = _pulseController.value;
    double opacity;
    if (t < 0.1) {
      opacity = t / 0.1;
    } else if (t > 0.9) {
      opacity = (1 - t) / 0.1;
    } else {
      opacity = 1.0;
    }
    final double leftFraction = 0.16 + (0.84 - 0.16) * t;
    final double centerX = leftFraction * wrapWidth;

    return PositionedDirectional(
      top: 31,
      start: centerX - 5,
      child: Opacity(
        opacity: _pulseController.isAnimating ? opacity.clamp(0.0, 1.0) : 0.0,
        child: Container(
          width: 10,
          height: 10,
          decoration: const BoxDecoration(
            color: AppColors.primary,
            shape: BoxShape.circle,
          ),
        ),
      ),
    );
  }

  Widget _buildNode({
    required String label,
    required Color background,
    required Color textColor,
    Border? border,
  }) {
    return Container(
      width: 46,
      height: 46,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        color: background,
        borderRadius: BorderRadius.circular(14),
        border: border,
      ),
      child: Text(
        label,
        style: AppTextStyles.avatarInitials.copyWith(color: textColor),
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/consent_success_view.dart
// ---------------------------------------------------------------
class ConsentSuccessView extends StatelessWidget {
  const ConsentSuccessView({
    super.key,
    required this.active,
    required this.onDonePressed,
  });

  final bool active;
  final VoidCallback onDonePressed;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return Padding(
      padding: const EdgeInsetsDirectional.fromSTEB(6, 14, 6, 4),
      child: Column(
        children: [
          SuccessLinkGraphic(active: active),
          const SizedBox(height: 20),
          Text(
            scope.t('family_successTitle'),
            textAlign: TextAlign.center,
            style: AppTextStyles.successHeading.copyWith(color: theme.AppColors.textP(context)),
          ),
          const SizedBox(height: 6),
          SizedBox(
            width: 220,
            child: Text(
              scope.t('family_successSubtitle'),
              textAlign: TextAlign.center,
              style: AppTextStyles.successParagraph.copyWith(color: theme.AppColors.textS(context)),
            ),
          ),
          const SizedBox(height: 20),
          AppPrimaryButton(
            label: scope.t('family_doneBtn'),
            enabled: true,
            loading: false,
            mutedStyle: true,
            onPressed: onDonePressed,
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/info_card.dart
// ---------------------------------------------------------------
class InfoCard extends StatelessWidget {
  const InfoCard({
    super.key,
    required this.icon,
    required this.title,
    required this.bullets,
    this.marginBottom = 12,
  });

  final IconData icon;
  final String title;
  final List<String> bullets;
  final double marginBottom;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsetsDirectional.only(bottom: marginBottom),
      padding: const EdgeInsetsDirectional.symmetric(horizontal: 18, vertical: 16),
      decoration: BoxDecoration(
        color: theme.AppColors.cardBgOf(context),
        border: Border.all(color: theme.AppColors.border(context)),
        borderRadius: BorderRadius.circular(AppColors.radiusLg),
        boxShadow: const [
          BoxShadow(
            color: AppColors.cardShadow,
            blurRadius: 3,
            offset: Offset(0, 1),
          ),
        ],
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 34,
            height: 34,
            margin: const EdgeInsetsDirectional.only(top: 1),
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: AppColors.primaryTint,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(icon, size: 16, color: AppColors.primary),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: AppTextStyles.infoCardTitle.copyWith(color: theme.AppColors.textP(context))),
                const SizedBox(height: 7),
                for (final bullet in bullets) _buildBullet(bullet, context),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBullet(String text, BuildContext context) {
    return Padding(
      padding: const EdgeInsetsDirectional.only(bottom: 5),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsetsDirectional.only(top: 7),
            child: Container(
              width: 5,
              height: 5,
              decoration: const BoxDecoration(
                color: AppColors.primary,
                shape: BoxShape.circle,
              ),
            ),
          ),
          const SizedBox(width: 9),
          Expanded(child: Text(text, style: AppTextStyles.infoCardBullet.copyWith(color: theme.AppColors.textS(context)))),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/permissions_section.dart
// ---------------------------------------------------------------
class PermissionsSection extends StatelessWidget {
  const PermissionsSection({super.key});

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SectionEyebrow(scope.t('family_permOverviewLabel')),
        InfoCard(
          icon: Icons.favorite_border,
          title: scope.t('family_permCollectedTitle'),
          bullets: [
            scope.t('family_permCollectedBullet1'),
            scope.t('family_permCollectedBullet2'),
            scope.t('family_permCollectedBullet3'),
          ],
        ),
        InfoCard(
          icon: Icons.shield_outlined,
          title: scope.t('family_permUsedTitle'),
          bullets: [
            scope.t('family_permUsedBullet1'),
            scope.t('family_permUsedBullet2'),
            scope.t('family_permUsedBullet3'),
          ],
        ),
        InfoCard(
          icon: Icons.verified_user_outlined,
          title: scope.t('family_permPrivacyTitle'),
          bullets: [
            scope.t('family_permPrivacyBullet1'),
            scope.t('family_permPrivacyBullet2'),
            scope.t('family_permPrivacyBullet3'),
          ],
          marginBottom: 0,
        ),
      ],
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/family_member_row.dart
// ---------------------------------------------------------------
class FamilyMemberRow extends StatelessWidget {
  const FamilyMemberRow({
    super.key,
    required this.member,
    this.showBottomBorder = true,
    this.onConnectTap,
  });

  final FamilyMember member;
  final bool showBottomBorder;
  final VoidCallback? onConnectTap;

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    final bool isConnected = member.status == FamilyMemberStatus.connected;
    String? displayName;
    String? displayRel;
    switch (member.initials) {
      case 'PA':
        displayName = scope.t('family_memberParentName');
        displayRel = scope.t('family_memberParentRel');
        break;
      case 'CH':
        displayName = scope.t('family_memberChildName');
        displayRel = scope.t('family_memberChildRel');
        break;
      case 'SI':
        displayName = scope.t('family_memberSiblingName');
        displayRel = scope.t('family_memberSiblingRel');
        break;
    }

    return Container(
      padding: const EdgeInsetsDirectional.symmetric(horizontal: 4, vertical: 12),
      decoration: BoxDecoration(
        border: showBottomBorder
            ? Border(bottom: BorderSide(color: theme.AppColors.border(context)))
            : null,
      ),
      child: Row(
        children: [
          _buildAvatar(isConnected, context),
          const SizedBox(width: 13),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(displayName ?? member.name, style: AppTextStyles.memberName.copyWith(color: theme.AppColors.textP(context))),
                const SizedBox(height: 1),
                Text(displayRel ?? member.relationship, style: AppTextStyles.memberRel.copyWith(color: theme.AppColors.mutedOf(context))),
              ],
            ),
          ),
          StatusPill(status: member.status, onConnectTap: onConnectTap),
        ],
      ),
    );
  }

  Widget _buildAvatar(bool isConnected, BuildContext context) {
    final Widget avatar = Container(
      width: 46,
      height: 46,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        color: member.tintedAvatar ? AppColors.primaryTint : theme.AppColors.surf(context),
        borderRadius: BorderRadius.circular(14),
      ),
      child: Text(
        member.initials,
        style: member.tintedAvatar
            ? AppTextStyles.avatarInitialsTint
            : AppTextStyles.avatarInitials.copyWith(color: theme.AppColors.textP(context)),
      ),
    );

    if (!isConnected) return avatar;

    // Recreates `.avatar .ring` — an absolutely positioned border sitting
    // 3px outside the avatar box, only visible on the connected member.
    return Stack(
      clipBehavior: Clip.none,
      children: [
        avatar,
        PositionedDirectional(
          start: -3,
          end: -3,
          top: -3,
          bottom: -3,
          child: DecoratedBox(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: AppColors.success, width: 1.5),
            ),
          ),
        ),
      ],
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/widgets/family_card.dart
// ---------------------------------------------------------------
class FamilyCard extends StatelessWidget {
  const FamilyCard({super.key, required this.members, this.onConnectTap});

  final List<FamilyMember> members;
  final ValueChanged<FamilyMember>? onConnectTap;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsetsDirectional.all(18),
      decoration: BoxDecoration(
        color: theme.AppColors.cardBgOf(context),
        border: Border.all(color: theme.AppColors.border(context)),
        borderRadius: BorderRadius.circular(AppColors.radiusLg),
        boxShadow: const [
          BoxShadow(
            color: AppColors.cardShadow,
            blurRadius: 3,
            offset: Offset(0, 1),
          ),
        ],
      ),
      child: Column(
        children: [
          for (int i = 0; i < members.length; i++)
            FamilyMemberRow(
              member: members[i],
              showBottomBorder: i != members.length - 1,
              onConnectTap: onConnectTap == null
                  ? null
                  : () => onConnectTap!(members[i]),
            ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: family_account_consent/pages/family_account_consent_page.dart
// ---------------------------------------------------------------
class FamilyAccountConsentPage extends StatefulWidget {
  const FamilyAccountConsentPage({super.key});

  @override
  State<FamilyAccountConsentPage> createState() =>
      _FamilyAccountConsentPageState();
}

class _FamilyAccountConsentPageState extends State<FamilyAccountConsentPage> {
  bool _consentChecked = false;
  bool _isConnecting = false;
  bool _showSuccess = false;

  final List<FamilyMember> _members = const [
    FamilyMember(
      initials: 'PA',
      name: 'Parent',
      relationship: 'Parent',
      status: FamilyMemberStatus.connected,
      tintedAvatar: true,
    ),
    FamilyMember(
      initials: 'CH',
      name: 'Child',
      relationship: 'Child',
      status: FamilyMemberStatus.pending,
    ),
    FamilyMember(
      initials: 'SI',
      name: 'Sibling',
      relationship: 'Sibling',
      status: FamilyMemberStatus.connectable,
    ),
  ];

  void _handleConnectPressed() {
    if (!_consentChecked || _isConnecting) return;
    setState(() => _isConnecting = true);
    // Matches the original setTimeout(..., 1200) "Connecting…" delay before
    // swapping to the success panel.
    Future.delayed(const Duration(milliseconds: 1200), () {
      if (!mounted) return;
      setState(() {
        _isConnecting = false;
        _showSuccess = true;
      });
    });
  }

  void _handleDonePressed() {
    Navigator.of(context).maybePop(true);
  }

  void _handleNotNowPressed() {
    Navigator.of(context).maybePop(false);
  }

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return Scaffold(
      backgroundColor: theme.AppColors.bg(context),
      body: SafeArea(
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 412),
            child: SingleChildScrollView(
              padding:
                  const EdgeInsetsDirectional.symmetric(horizontal: 16, vertical: 48),
              child: Container(
                width: double.infinity,
                padding: const EdgeInsetsDirectional.fromSTEB(20, 28, 20, 32),
                decoration: BoxDecoration(
                  color: theme.AppColors.bg(context),
                  border: Border.all(color: theme.AppColors.border(context)),
                  borderRadius: BorderRadius.circular(32),
                  boxShadow: const [
                    BoxShadow(
                      color: AppColors.screenShadow,
                      blurRadius: 24,
                      offset: Offset(0, 4),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    BrandHeader(onClose: () => Navigator.of(context).maybePop(false)),
                    const SizedBox(height: 22),
                    Text(scope.t('family_safetyTitle'), style: AppTextStyles.heading1.copyWith(color: theme.AppColors.textP(context))),
                    const SizedBox(height: 8),
                    SizedBox(
                      width: 230,
                      child: Text(
                        scope.t('family_safetySubtitle'),
                        style: AppTextStyles.headerParagraph.copyWith(color: theme.AppColors.textS(context)),
                      ),
                    ),
                    const SizedBox(height: 26),
                    Padding(
                      padding: const EdgeInsetsDirectional.only(bottom: 20),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          SectionEyebrow(scope.t('family_yourFamilyLabel')),
                          FamilyCard(members: _members),
                        ],
                      ),
                    ),
                    const Padding(
                      padding: EdgeInsetsDirectional.only(bottom: 20),
                      child: PermissionsSection(),
                    ),
                    _showSuccess
                        ? ConsentSuccessView(
                            active: _showSuccess,
                            onDonePressed: _handleDonePressed,
                          )
                        : ConsentDefaultView(
                            consentChecked: _consentChecked,
                            onConsentChanged: (value) =>
                                setState(() => _consentChecked = value),
                            isConnecting: _isConnecting,
                            onConnectPressed: _handleConnectPressed,
                            onNotNowPressed: _handleNotNowPressed,
                          ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------
// from: main.dart (app + entry point)
// ---------------------------------------------------------------
void main() {
  runApp(const AxnSafetyApp());
}

class AxnSafetyApp extends StatelessWidget {
  const AxnSafetyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final scope = AppScope.of(context);
    return MaterialApp(
      title: scope.t('family_appTitle'),
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        scaffoldBackgroundColor: theme.AppColors.getBg(true),
        
        fontFamily: GoogleFonts.inter().fontFamily,
        textTheme: GoogleFonts.interTextTheme(),
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        scaffoldBackgroundColor: theme.AppColors.getBg(false),
        brightness: Brightness.dark,
        fontFamily: GoogleFonts.inter().fontFamily,
        textTheme: GoogleFonts.interTextTheme(
          ThemeData(brightness: Brightness.dark).textTheme,
        ),
      ),
      home: const FamilyAccountConsentPage(),
    );
  }
}
